language: python
python:
- '3.6'
- '3.7-dev'
cache: pip
env:
- PIPENV_VENV_IN_PROJECT=true
before_install:
- pip install -U pip pipenv
install:
- pipenv install --dev --deploy
script:
- pytest tests/
notifications:
  slack:
    secure: i1b73+7unXWhjC6iFWAXzlgPoc5v8uiiUWTU0CM6BmAorHiwAmZrmIhp6cCyYR7O3n5244+yK65IrmI9R6G8cEObFat0dU18fCtfbz9kOBsgGLpfQnS70rWacSC4o+hAbOps79Ib+YF2HU2SEucDSr21gQt1BnrWSzQm3/J00z3yHWwiTAFXoffwr/n1LUmqqH9/lgkALMeZ5zSFzib4h0MCMXOxQapkRW6of2rRGA21nxsAAR9ZYIRmY9P+P8oju5Vyf3gDI2XcMmBp64MExxq1W/9LPk2GIyMGAH+clbfOxcpLF7UKMXQUqO0t3rnFA3tgC1Pfo+J/Ymk5S4uldQzOREyclyHQqa9WSxB8AnPilz2kBOM4JHh0csoBHYuJ2cpGg3vk1+CXd9kaFEjSEpNpHcIKrrxlq7JMF5dGlVvsrRtVn0v7HoRkyiA55BleB5OkYJIs1s6U8PZgTFJQqtlAz8EU+tckGviOQvPbUZVQ+4j3w3hUfA3/3IEz6I++uQZke0PdQkIDGVA9Me3zdkceXWgmsxFa+3eFmwgHERNVMJ351tDCIBtLeHtX1HN8MdsYG4PaOG7w8ENrHYYGxOQGF1M/uUrpLajhd+ykAKvXKY/Z0I0d+7xVX8KvYn9PFCFhyvEPgDhTyd95gJkR5SOqALvt+JngAPqJCrP0RaA=
  email: false
before_deploy: "echo 'Uploading the package to PyPI...'"
deploy:
  provider: pypi
  user: "KeltonKarboviak"
  password:
    secure: apHrZaeG0wUyKlJZ+95yOGiUL9ru8tauQTG/TSdkQK1psVNrC21kXquE51XBZXJLIRBSUvfwOhL8zm6CEa/CNoiB6668MNqDxbcB9nOowFAw1jIJxruOwJjEyibOW9iCAIhRMSaMfSRqi3qbRDNtQENla5PVCe7jjPdRiOjQtIXCLiRqfolj0M7EZrtnW9S0hW1eyAVlYLUqCcg1+YinbdLYZqzom5e8LMoSEUmkoV/JYkzIeIbj2vH2gavGSYRZ+muucBfUd3yz+rJdFs6AMcS+4M5sf0nXetkyMV+RGH8EhvoLEuarek3Zw2okomg7g27gc5pUWqUP4HH6KFUVPw0ES6+SWYAaXoIwhSEjOAutvItLVaqr/pHpRV0nFsAWoN+f78+6t0JzeGt19V4ejyas55CZFSNm5yXD/1qWOY7KVpvjD3ST+8Bio6XEk6jdWqjNW15AwU7VwcDYDQCRQnz0aAhl3x0wBFXprcWH8RUVt3nvBQAp8BJwuAvHzN+XMliOCiOrouxSCA8maC9G83PpPyILzNeGJT4a+kpWo1bqO7rzGZxAIvRRtG+2G8+3qTnBEGkCGIsXKt5pEPNVx2uhOtGEJStY+Po6CKwGJBnXDQ9Mrpl/Zyhi12FSWMvE2uTwJbtzWhc4rr6D45z+DyS9bKIJ6N1Dvn2De1KxVUc=
  on:
    tags: true
    python: '3.6'
